# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Steve Heim
tagline:             ' '
description:         'Too few samples to infer a description.' # <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.
url:                 sheim.github.io
gems:                [jekyll-paginate]
markdown:            redcarpet
# baseurl:             ''
paginate:            3
paginate_path:       "page:num"


# About/contact
author:
  name:              Steve Heim
  url:               https://dlg.is.mpg.de/person/heim #http://www.cmplx.riec.tohoku.ac.jp/
  email:             heim.steve@gmail.com

# Custom vars
version:             1.0.0
