# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Steve Heim
tagline:             ' '
description:         'Musings of my life as a grad student in Japan' # <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.
# url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Steve Heim
  url:               http://www.cmplx.riec.tohoku.ac.jp/
  email:             heim.steve@gmail.com

# Custom vars
version:             1.0.0
